package diff05;

import java.io.IOException;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import Tools.Timer;

//How many distinct terms are in the sequence generated by 
//	a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

public class Problem030 {

	public static void main(String[] args) throws InterruptedException, IOException {

		Timer timer = new Timer();

		Set<BigDecimal> numbers = new HashSet<BigDecimal>();
		int limit = 100;
		
		for (int a = 2; a <= limit; a++) {
			for (int b = 2; b <= limit; b++) {
				BigDecimal cur = new BigDecimal(Math.pow(a, b));
				numbers.add(cur);
			}

		}
		System.out.println(numbers.size());
		
		timer.stopWatch();
	}
}