package diff05;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import Tools.Pandigital;
import Tools.Timer;

//How many distinct terms are in the sequence generated by 
//	a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

public class Problem032 {

	public static void main(String[] args) throws InterruptedException, IOException {

		Timer timer = new Timer();

		List<Long> products = new ArrayList<Long>();
		

		long prod = 0;
		int nStart = 0;
		
		for (long m = 2; m < 100; m++) { 
			if(m > 9){
				nStart = 123;
			}else{
				nStart = 1234;
			}
			long nEnd = 10000 / m + 1;
			
			for (long n = nStart; n < nEnd; n++) { 
				String tot = "";
				prod = m * n; 
				tot += String.valueOf(m)+String.valueOf(n)+String.valueOf(prod);
				if(tot.length() == 9 && Pandigital.isPandigital(Long.valueOf(tot),9) && !products.contains(prod)){
					products.add(prod);
				}
			}
		}
		long out = 0;
			for (Long long1 : products) {
				out += long1;
			}
			
		System.out.println(products.size() );
		System.out.println(out);
		
		timer.stopWatch();
		
		
	}
}