package diff05;

import java.io.IOException;

import Tools.Timer;

//How many distinct terms are in the sequence generated by 
//	a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

public class Problem029 {

	public static void main(String[] args) throws InterruptedException, IOException {

		Timer timer = new Timer();

		int result = 0;
		 
		for (int i = 2; i < 355000; i++) { int sumOfPowers = 0; int number = i; while (number > 0) {
		        int d = number % 10;
		        number /= 10;
		 
		        int temp = d;
		        for(int j = 1; j < 5; j++){
		            temp *= d;
		        }
		        sumOfPowers += temp;
		    }
		 
		    if (sumOfPowers == i) {
		        result += i;
		    }
		}
		System.out.println(result);
		
		timer.stopWatch();
	}
}