package diff05;

import java.io.IOException;

import Tools.MyMaths;
import Tools.Timer;

//How many distinct terms are in the sequence generated by 
//	a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

public class Problem033 {

	public static void main(String[] args) throws InterruptedException, IOException {

		Timer timer = new Timer();

		int numer = 1;
		int denom = 1;
		for (int d = 10; d < 100; d++) {
			for (int n = 10; n < d; n++) {
				int n0 = n % 10, n1 = n / 10;
				int d0 = d % 10, d1 = d / 10;
				if (n1 == d0 && n0 * d == n * d1 || n0 == d1 && n1 * d == n * d0) {
					numer *= n;
					denom *= d;
				}
			}
		}
		
		System.out.println(denom / MyMaths.highComDenom(numer,denom));
	
		timer.stopWatch();
		
		
	}
}